/**
 * This script initializes the RMU Complementary Skills module.
 * It imports the unified application class, registers Handlebars helpers,
 * and injects the control button into the Foundry UI.
 */

import { ComplementarySkillsApp } from "./src/ComplementarySkillsApp.js";
import { RMUSkillParser } from "./src/RMUSkillParser.js";
import { VALID_ACTOR_TYPES } from "./src/config.js";

/**
 * Registers Handlebars helpers used across the module's templates.
 */
Hooks.once("init", () => {
    Handlebars.registerHelper("rmucsSelected", function (condition) {
        return condition ? "selected" : "";
    });
    Handlebars.registerHelper("checked", function (condition) {
        return condition ? "checked" : "";
    });
    Handlebars.registerHelper("disabled", function (condition) {
        return condition ? "disabled" : "";
    });
    Handlebars.registerHelper("eq", function (a, b) {
        return a === b;
    });
    Handlebars.registerHelper("not", function (a) {
        return !a;
    });

    // Formats a number to always show a sign (+5, -2, +0)
    Handlebars.registerHelper("signed", function (value) {
        const num = Number(value);
        if (isNaN(num)) return value;
        return new Intl.NumberFormat(game.i18n.lang, {
            signDisplay: "always",
        }).format(num);
    });
});

/**
 * Exposes the application classes to the game object for global access.
 */
Hooks.once("ready", () => {
    try {
        game.rmuComplementarySkills = {
            ComplementarySkillsApp,
            RMUSkillParser,
            VALID_ACTOR_TYPES,
        };
    } catch (error) {
        console.error("RMU COMP SKILLS | Failed to register application classes:", error);
    }
});

/**
 * Hooks into chat message rendering to attach roll logic to the custom buttons
 * generated by the ComplementarySkillsApp.
 */
Hooks.on("renderChatMessageHTML", (message, html) => {
    const flags = message.flags?.["rmu-complementary-skills"];
    if (!flags?.isCalc) return;

    const $html = $(html);
    $html.addClass("rmu-calc-message");

    // Apply RTL support to the chat message wrapper
    const rtlLanguages = ["ar", "he", "fa", "ur"];
    if (rtlLanguages.includes(game.i18n.lang)) {
        $html.attr("dir", "rtl");
        $html.addClass("rtl");
    }

    const $button = $html.find(".rmu-roll-skill-button");
    if ($button.length === 0) return;

    const { rollType, actorId, skillUuid, bonus } = flags;

    $button.on("click", async (ev) => {
        // Find the token owned by the user that matches the actor ID
        const token = canvas.tokens.ownedTokens.find((t) => t.actor?.id === actorId);

        if (!token?.actor) {
            ui.notifications.warn(
                game.i18n.format("RMU_CS.Notifications.TokenRequired", {
                    name: actorId,
                }),
            );
            return;
        }

        const skillObject = RMUSkillParser.getRawSkillById(token.actor, skillUuid);

        if (!skillObject) {
            ui.notifications.error(game.i18n.localize("RMU_CS.Notifications.SkillNotFound"));
            return;
        }

        const maneuverOptions = {};
        if (rollType === "boost") {
            maneuverOptions.otherBonus = Number(bonus);
        } else if (rollType === "group") {
            maneuverOptions.overrideSkillBonus = Number(bonus);
        }

        if (game.system?.api?.rmuTokenSkillAction) {
            game.system.api.rmuTokenSkillAction(token, skillObject, maneuverOptions);
        } else {
            ui.notifications.error(game.i18n.localize("RMU_CS.Notifications.ApiNotFound"));
        }
    });
});

/**
 * Injects a new tool button into the Token Controls menu for Game Masters.
 * Clicking this button launches the unified ComplementarySkillsApp.
 */
Hooks.on("getSceneControlButtons", (controls) => {
    if (!game.user.isGM) return;

    // Locate the token controls section using the original safe loop
    let tokenControls = null;
    for (const key in controls) {
        if (controls[key].name === "tokens") {
            tokenControls = controls[key];
            break;
        }
    }

    if (tokenControls) {
        // Revert to the original explicit property assignment
        tokenControls.tools["rmu-complementary-skills"] = {
            name: "rmu-complementary-skills",
            title: "RMU_CS.Title",
            icon: "rmu-skill-button-icon",
            button: true,
            onChange: () => {
                if (!game.rmuComplementarySkills?.ComplementarySkillsApp) {
                    console.error("RMU COMP SKILLS | Button clicked, but app is not registered.");
                    ui.notifications.error(game.i18n.localize("RMU_CS.Notifications.NotInitialized"));
                    return;
                }

                // Gather controlled tokens and filter out invalid types
                const controlledTokens = canvas.tokens.controlled;
                const validTokens = controlledTokens.filter((t) => t.actor && VALID_ACTOR_TYPES.includes(t.actor.type));

                if (validTokens.length === 0) {
                    ui.notifications.warn(game.i18n.localize("RMU_CS.Notifications.SelectOne"));
                    return;
                }

                // Render the unified application, forcing a fresh context load
                new game.rmuComplementarySkills.ComplementarySkillsApp(validTokens).render({ force: true });
            },
        };
    }
});
