/**
 * This script initializes the RMU Complementary Skills module.
 * It imports the unified application class, registers Handlebars helpers,
 * and injects the control button into the Foundry UI.
 */

import { ComplementarySkillsApp } from "./src/ComplementarySkillsApp.js";
import { RMUSkillParser } from "./src/RMUTokenParser.js";
import { ChatManager } from "./src/ChatManager.js";
import { VALID_ACTOR_TYPES } from "./src/config.js";

/**
 * Applies the selected hue class to the Foundry document body.
 * @param {string} hue - The hue string ('gold' or 'teal').
 */
function applyThemeHue(hue) {
    document.body.classList.remove("rmucsc-hue-gold", "rmucsc-hue-teal");
    document.body.classList.add(`rmucsc-hue-${hue}`);
}

/**
 * Registers Handlebars helpers used across the module's templates.
 */
Hooks.once("init", () => {
    game.settings.register("rmu-complementary-skills", "themeHue", {
        name: "RMU_CS.Settings.ThemeHue.Name",
        hint: "RMU_CS.Settings.ThemeHue.Hint",
        scope: "client",
        config: true,
        type: String,
        choices: {
            gold: "RMU_CS.Settings.ThemeHue.Gold",
            teal: "RMU_CS.Settings.ThemeHue.Teal",
        },
        default: "gold",
        onChange: (value) => applyThemeHue(value),
    });

    game.settings.register("rmu-complementary-skills", "ritualPresets", {
        scope: "world",
        config: false,
        type: Array,
        default: [],
    });

    Handlebars.registerHelper("rmucsSelected", function (condition) {
        return condition ? "selected" : "";
    });
    Handlebars.registerHelper("checked", function (condition) {
        return condition ? "checked" : "";
    });
    Handlebars.registerHelper("disabled", function (condition) {
        return condition ? "disabled" : "";
    });
    Handlebars.registerHelper("eq", function (a, b) {
        return a === b;
    });
    Handlebars.registerHelper("not", function (a) {
        return !a;
    });

    // Formats a number to always show a sign (+5, -2, +0)
    Handlebars.registerHelper("signed", function (value) {
        const num = Number(value);
        if (Number.isNaN(num)) return value;
        return new Intl.NumberFormat(game.i18n.lang, {
            signDisplay: "always",
        }).format(num);
    });
});

/**
 * Exposes the application classes to the game object for global access.
 */
Hooks.once("ready", () => {
    try {
        game.rmuComplementarySkills = {
            ComplementarySkillsApp,
            RMUSkillParser,
            VALID_ACTOR_TYPES,
        };
    } catch (error) {
        console.error("RMU COMP SKILLS | Failed to register application classes:", error);
    }
});

/**
 * Hooks into chat message rendering to attach roll logic to the custom buttons
 * generated by ChatManager.
 */
Hooks.on("renderChatMessageHTML", (message, html) => {
    ChatManager.onRenderChatMessage(message, html);
});

/**
 * Injects a new tool button into the Token Controls menu for Game Masters.
 * Clicking this button launches the unified ComplementarySkillsApp.
 */
Hooks.on("getSceneControlButtons", (controls) => {
    if (!game.user.isGM) return;

    // Locate the token controls section using the original safe loop
    let tokenControls = null;
    for (const key in controls) {
        if (controls[key].name === "tokens") {
            tokenControls = controls[key];
            break;
        }
    }

    if (tokenControls) {
        // Revert to the original explicit property assignment
        tokenControls.tools["rmu-complementary-skills"] = {
            name: "rmu-complementary-skills",
            title: "RMU_CS.Title",
            icon: "rmucsc-skill-button-icon",
            button: true,
            onChange: () => {
                if (!game.rmuComplementarySkills?.ComplementarySkillsApp) {
                    console.error("RMU COMP SKILLS | Button clicked, but app is not registered.");
                    ui.notifications.error(game.i18n.localize("RMU_CS.Notifications.NotInitialized"));
                    return;
                }

                // Gather controlled tokens and filter out invalid types
                const controlledTokens = canvas.tokens.controlled;
                const validTokens = controlledTokens.filter((t) => t.actor && VALID_ACTOR_TYPES.includes(t.actor.type));

                if (validTokens.length === 0) {
                    ui.notifications.warn(game.i18n.localize("RMU_CS.Notifications.SelectOne"));
                    return;
                }

                // Render the unified application, forcing a fresh context load
                new game.rmuComplementarySkills.ComplementarySkillsApp(validTokens).render({ force: true });
            },
        };
    }
});
